### ISSUE TITLE
Support random board generation

### ISSUE THREAD

**Issue by Him188** [keizar24/keizar#4]
Game stup:
- Allocate random black or white colour to players
- The board should be visible to players.

Board components:
- Place KEIZÁR tile on middle white square of black side centre.
- Place plain black and white tiles in pattern
- Place all other tiles randomly per side
- Place pieces on first two rows
- Place counter tokens

**Comment by Him188** [comment]
@JerryZ233 Can you confirm this has done

**Comment by JerryZ233** [comment]
Done except "Allocate random black or white colour to players". Opened a new issue #17 on this.
